import streamlit as st
with st.container():
    # col1, col2 = st.columns((2,4))
    # with col1():
    #     st.text("This project was created for Team Enegy, a Group of Data Sciance students attending Le Wagon London, a Coding & Data Sciace Bootcamp. This Project was our Final Challange while at the Bootcamp and shows of our skills in the Following areas:")
    #     st.text("Python")
    #     st.text("-| Python for Data Science")
    #     st.text("-| Data Sourcing SQL")
    #     st.text("-| Creating & Quearing a Database")
    #     st.text("-| Calling SQL inside of Python DATA.")
    #     st.text("-| Data Analysis")
    #     st.text("-| Data Sourcing Data")
    #     st.text("-| Visualization")
    #     st.text("-| Visualization")
    #     st.text("-| DataSciance")
    #     st.text("-| Related Maths")
    #     st.text("-| Algebra & Calculus with Scipy Statistics & Probabilities")
    #     st.text("-|- Statistics & Probabilities")
    #     st.text("-|- Bayes Theorem")
    #     st.text("-|- Markov Chains Decision Science")
    #     st.text("-| Mashine Learning Deap Learning")
    #     st.text("-| Google Cloud Platform (GCP)")
    # with col2():
    #     st.empty()
        st.markdown("This project was created for Team Enegy, a Group of Data Sciance")
        st.markdown("students attending Le Wagon London, a Coding & Data Sciace Bootcamp.")
        st.markdown("This Project was our Final Challange while at the Bootcamp and shows")
        st.markdown("of our skills in the Following areas:")
        st.subheader("Python")
        st.markdown("1. Python for Data Science")
        st.markdown("-| Data Sourcing SQL")
        st.markdown("-| Creating & Quearing a Database")
        st.markdown("-| Calling SQL inside of Python DATA.")
        st.markdown("-| Data Analysis")
        st.markdown("-| Data Sourcing Data")
        st.markdown("-| Visualization")
        st.markdown("-| Visualization")
        st.markdown("-| DataSciance")
        st.markdown("-| Related Maths")
        st.markdown("-| Algebra & Calculus with Scipy Statistics & Probabilities")
        st.markdown("-|- Statistics & Probabilities")
        st.markdown("-|- Bayes Theorem")
        st.markdown("-|- Markov Chains Decision Science")
        st.markdown("-| Mashine Learning Deap Learning")
        st.markdown("-| Google Cloud Platform (GCP)")
